version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/.:/app/src/.
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env